### ISSUE TITLE
How to detect no records scenarios when observing childevents

### ISSUE THREAD

**Issue by abhishekBansal** [FrangSierra/RxFirebase#52]
observeChildEvents return flowables which do not complete when there are no records in database. If I have to show an emptyview how do I go about it? How do I check if there are no records in database.

**Comment by FrangSierra** [comment]
`observeChildEvents` is a Flowable. If it's call `onComplete ` when there is no data. Your Flowable will be disposed and even if you recieve new items they will not be emmited. This is how Firebase works too without the library wrapper. 

You open a listener for listen childs, if there is no childs, there is no callbacks. 
If you wanna show a "there is no data" message or something like that. I suggest you to use `observeSingleEventListener` which is a Maybe and will return `onComplete` if there is not data. 

Anyway, the result that you will have using a `observeChildEvents` that calls `onComplete` if there is not data will be the same, because your subscription will be dispose after `onComplete`
