### ISSUE TITLE
Query multiple documents

### ISSUE THREAD

**Issue by lawloretienne** [FrangSierra/RxFirebase#75]
You can query for a single document like it shows here :

https://github.com/FrangSierra/RxFirebase#firestore

However what if you want to query for multiple documents and return that in a Maybe<>.  How would you go about that?

something like this

```
validSpotIds.forEach { validSpotId ->
            RxFirestore.getDocument(collectionRef.document(validSpotId.toString()))
                    .map { it.data }
                    .map { it.get("forecasts") }
                    .map { (it as ArrayList<HashMap<String, Object>>)[currentHour] }
                    .filter { (it.get("shape_full") as String).equals("Good")
                            || (it.get("shape_full") as String).equals("Fair-Good")}
                    .doOnSuccess { forecast -> Timber.d("forecast - "+forecast) }
                    .subscribe { spotData -> Timber.d("Finished")}
        }
```

However i wouldn't want to call subscribe here, i want to build up an rxchain that returns a Maybe.

**Comment by FrangSierra** [comment]
Instead of a document get a collection with some filter params, if not, you can do multiple calls to `getdocument` and put them in a `zip` call. Also, unify all the calls in a single `map` for better performance.

I invite you to read more about how RxJava 2.0 works before start using Firestore that much. The library itself is a wrapper to port firebase to reactive model.
